// Lista completa de bancos brasileiros (códigos BACEN oficiais)
// Arquivo separado para evitar export inválido em Next.js page files

export interface BancoBR {
  codigo: string
  nome: string
}

export const BANCOS_BR = [
  { codigo: '001', nome: 'Banco do Brasil S.A.' },
  { codigo: '003', nome: 'Banco da Amazônia S.A.' },
  { codigo: '004', nome: 'Banco do Nordeste do Brasil S.A.' },
  { codigo: '010', nome: 'Credicoamo Crédito Rural Cooperativa' },
  { codigo: '021', nome: 'Banestes S.A. Banco do Estado do Espírito Santo' },
  { codigo: '025', nome: 'Banco Alfa S.A.' },
  { codigo: '033', nome: 'Banco Santander (Brasil) S.A.' },
  { codigo: '036', nome: 'Banco Bradesco BBI S.A.' },
  { codigo: '037', nome: 'Banco do Estado do Pará S.A.' },
  { codigo: '040', nome: 'Banco Cargill S.A.' },
  { codigo: '041', nome: 'Banco do Estado do Rio Grande do Sul S.A. (Banrisul)' },
  { codigo: '047', nome: 'Banco do Estado de Sergipe S.A. (Banese)' },
  { codigo: '062', nome: 'Hipercard Banco Múltiplo S.A.' },
  { codigo: '063', nome: 'Banco Bradescard S.A.' },
  { codigo: '069', nome: 'Banco Crefisa S.A.' },
  { codigo: '070', nome: 'BRB – Banco de Brasília S.A.' },
  { codigo: '077', nome: 'Banco Inter S.A.' },
  { codigo: '082', nome: 'Banco Topázio S.A.' },
  { codigo: '084', nome: 'Uniprime Norte do Paraná – Cooperativa de Crédito' },
  { codigo: '085', nome: 'Cooperativa Central de Crédito – Ailos' },
  { codigo: '089', nome: 'Cooperativa de Crédito Rural da Região da Mogiana' },
  { codigo: '097', nome: 'Credisis – Central de Cooperativas de Crédito' },
  { codigo: '099', nome: 'Uniprime Central – Central Interestadual de Cooperativas de Crédito' },
  { codigo: '102', nome: 'XP Investimentos Corretora de Câmbio, Títulos e Valores Mobiliários S.A.' },
  { codigo: '104', nome: 'Caixa Econômica Federal' },
  { codigo: '107', nome: 'Banco Bocom BBM S.A.' },
  { codigo: '108', nome: 'PortoCred S.A. – Crédito, Financiamento e Investimento' },
  { codigo: '114', nome: 'Central Cooperativa de Crédito do Espírito Santo (Cecoop)' },
  { codigo: '117', nome: 'Advanced Corretora de Câmbio Ltda.' },
  { codigo: '119', nome: 'Banco Western Union do Brasil S.A.' },
  { codigo: '120', nome: 'Banco Rodobens S.A.' },
  { codigo: '121', nome: 'Banco Agibank S.A.' },
  { codigo: '122', nome: 'Banco Bradesco BERJ S.A.' },
  { codigo: '124', nome: 'Banco Woori Bank do Brasil S.A.' },
  { codigo: '125', nome: 'Brasil Plural S.A. – Banco Múltiplo' },
  { codigo: '126', nome: 'BR Partners Banco de Investimento S.A.' },
  { codigo: '128', nome: 'MS Bank S.A. Banco de Câmbio' },
  { codigo: '129', nome: 'UBS Brasil Banco de Investimento S.A.' },
  { codigo: '130', nome: 'Caruana S.A. – Sociedade de Crédito, Financiamento e Investimento' },
  { codigo: '131', nome: 'Tullett Prebon Brasil Corretora de Valores e Câmbio Ltda.' },
  { codigo: '132', nome: 'ICBC do Brasil Banco Múltiplo S.A.' },
  { codigo: '133', nome: 'Cresol – Confederação Nacional das Cooperativas Centrais de Crédito' },
  { codigo: '134', nome: 'BGC Liquidez Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '136', nome: 'Unicred do Brasil – Confederação Nacional das Cooperativas Centrais Unicred' },
  { codigo: '137', nome: 'Multimoney Financeira Ltda. – Crédito, Financiamento e Investimento' },
  { codigo: '138', nome: 'Get Money Corretora de Câmbio S.A.' },
  { codigo: '139', nome: 'Intesa Sanpaolo Brasil S.A. – Banco Múltiplo' },
  { codigo: '140', nome: 'Easynvest – Título Corretora de Valores SA' },
  { codigo: '142', nome: 'Broker Brasil Corretora de Câmbio Ltda.' },
  { codigo: '143', nome: 'Treviso Corretora de Câmbio S.A.' },
  { codigo: '144', nome: 'BEXS Banco de Câmbio S/A' },
  { codigo: '145', nome: 'Levycam – Corretora de Câmbio e Valores Ltda.' },
  { codigo: '146', nome: 'GUITTA Corretora de Câmbio Ltda.' },
  { codigo: '149', nome: 'Facta Financeira S.A. – Crédito, Financiamento e Investimento' },
  { codigo: '157', nome: 'ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '159', nome: 'Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor' },
  { codigo: '163', nome: 'Commerzbank Brasil S.A. – Banco Múltiplo' },
  { codigo: '169', nome: 'Banco Olé Consignado S.A.' },
  { codigo: '172', nome: 'Albatross Corretora de Câmbio e Valores S.A.' },
  { codigo: '173', nome: 'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '174', nome: 'Pernambucanas Financiadora S.A. – Crédito, Financiamento e Investimento' },
  { codigo: '177', nome: 'Guide Investimentos S.A. Corretora de Valores' },
  { codigo: '180', nome: 'CM Capital Markets Corretora de Câmbio, Títulos e Valores Mobiliários Ltda.' },
  { codigo: '183', nome: 'Socred S.A. – Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte' },
  { codigo: '184', nome: 'Banco Itaú BBA S.A.' },
  { codigo: '188', nome: 'Ativa Investimentos S.A. Corretora de Títulos, Câmbio e Valores' },
  { codigo: '189', nome: 'HS Financeira S.A. Crédito, Financiamento e Investimentos' },
  { codigo: '190', nome: 'Servicoop – Cooperativa de Crédito dos Servidores Públicos Estaduais do Rio Grande do Sul' },
  { codigo: '191', nome: 'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '193', nome: 'Frankfurt Trust Investimentos Ltda.' },
  { codigo: '194', nome: 'Valores e Metais Nova Era S.A. – Distribuidora de Títulos e Valores Mobiliários' },
  { codigo: '195', nome: 'Azimut Brasil Wealth Management Ltda.' },
  { codigo: '196', nome: 'Fair Corretora de Câmbio S.A.' },
  { codigo: '197', nome: 'Stone Pagamentos S.A.' },
  { codigo: '208', nome: 'Banco BTG Pactual S.A.' },
  { codigo: '212', nome: 'Banco Original S.A.' },
  { codigo: '213', nome: 'Banco Arbi S.A.' },
  { codigo: '217', nome: 'Banco John Deere S.A.' },
  { codigo: '218', nome: 'Banco BS2 S.A.' },
  { codigo: '222', nome: 'Banco Credit Agricole Brasil S.A.' },
  { codigo: '224', nome: 'Banco Fibra S.A.' },
  { codigo: '225', nome: 'Banco Cifra S.A.' },
  { codigo: '229', nome: 'Banco Cruzeiro do Sul S.A.' },
  { codigo: '230', nome: 'Unicard Banco Múltiplo S.A.' },
  { codigo: '233', nome: 'Banco Cifra S.A.' },
  { codigo: '237', nome: 'Banco Bradesco S.A.' },
  { codigo: '241', nome: 'Banco Clássico S.A.' },
  { codigo: '243', nome: 'Banco Máxima S.A.' },
  { codigo: '246', nome: 'Banco ABC Brasil S.A.' },
  { codigo: '249', nome: 'Banco Investcred Unibanco S.A.' },
  { codigo: '250', nome: 'BCV – Banco de Crédito e Varejo S.A.' },
  { codigo: '253', nome: 'Bexs Corretora de Câmbio S/A' },
  { codigo: '254', nome: 'Paraná Banco S.A.' },
  { codigo: '260', nome: 'Nu Pagamentos S.A. – Nubank' },
  { codigo: '265', nome: 'Banco Fator S.A.' },
  { codigo: '266', nome: 'Banco Cédula S.A.' },
  { codigo: '268', nome: 'Barigui Companhia Hipotecária' },
  { codigo: '269', nome: 'HSBC Brasil S.A. – Banco de Investimento' },
  { codigo: '271', nome: 'IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.' },
  { codigo: '272', nome: 'AGK Corretora de Câmbio S.A.' },
  { codigo: '273', nome: 'Cooperativa de Crédito Rural de São Miguel do Oeste – Sulcredi/São Miguel' },
  { codigo: '274', nome: 'BMP Money Plus Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte Ltda.' },
  { codigo: '276', nome: 'Senff S.A. – Crédito, Financiamento e Investimento' },
  { codigo: '278', nome: 'Genial Investimentos Corretora de Valores Mobiliários S.A.' },
  { codigo: '279', nome: 'Cooperativa de Crédito Rural de Primavera do Leste' },
  { codigo: '280', nome: 'Avista S.A. Crédito, Financiamento e Investimento' },
  { codigo: '281', nome: 'Cooperativa de Crédito Rural Coopavel' },
  { codigo: '283', nome: 'RB Capital Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '285', nome: 'Frente Corretora de Câmbio Ltda.' },
  { codigo: '286', nome: 'Cooperativa de Crédito Rural UniCred Centro Norte' },
  { codigo: '288', nome: 'Carol Distribuidora de Títulos e Valor Mobiliários Ltda.' },
  { codigo: '289', nome: 'EFX Corretora de Câmbio, Títulos e Valores Mobiliários Ltda.' },
  { codigo: '290', nome: 'Pagseguro Internet S.A.' },
  { codigo: '292', nome: 'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '293', nome: 'Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '296', nome: 'OZ Corretora de Câmbio S.A.' },
  { codigo: '298', nome: 'Vips Corretora de Câmbio e Valores Ltda.' },
  { codigo: '299', nome: 'Bank of America Merrill Lynch Banco Múltiplo S.A.' },
  { codigo: '300', nome: 'Banco de La Nación Argentina' },
  { codigo: '301', nome: 'BPP Instituição de Pagamento S.A.' },
  { codigo: '306', nome: 'Portopar Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '307', nome: 'Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '309', nome: 'Cambionet Corretora de Câmbio Ltda.' },
  { codigo: '310', nome: 'VORTX Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '315', nome: 'PI Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '318', nome: 'Banco BMG S.A.' },
  { codigo: '319', nome: 'OM Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '320', nome: 'China Union Pay' },
  { codigo: '321', nome: 'Crefaz Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte Ltda.' },
  { codigo: '322', nome: 'Cooperativa de Crédito Rural de Abelardo Luz – Sulcredi/Crediluz' },
  { codigo: '323', nome: 'Mercado Pago – Conta do Mercado Livre' },
  { codigo: '324', nome: 'Cartos Sociedade de Crédito Direto S.A.' },
  { codigo: '325', nome: 'Órama Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '326', nome: 'Parati – Crédito, Financiamento e Investimento S.A.' },
  { codigo: '328', nome: 'Cooperativa de Economia e Crédito Mútuo dos Fabricantes de Calçados de Sapiranga' },
  { codigo: '329', nome: 'QI Sociedade de Crédito Direto S.A.' },
  { codigo: '330', nome: 'Banco Bari de Investimentos e Financiamentos S.A.' },
  { codigo: '331', nome: 'Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '332', nome: 'Acesso Soluções de Pagamento S.A.' },
  { codigo: '335', nome: 'Banco Digio S.A.' },
  { codigo: '336', nome: 'Banco C6 S.A.' },
  { codigo: '340', nome: 'Super Pagamentos e Administração de Meios Eletrônicos S.A.' },
  { codigo: '341', nome: 'Itaú Unibanco S.A.' },
  { codigo: '342', nome: 'Creditas Sociedade de Crédito Direto S.A.' },
  { codigo: '343', nome: 'FFA Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte Ltda.' },
  { codigo: '348', nome: 'Banco XP S.A.' },
  { codigo: '349', nome: 'Al5 S.A. Crédito, Financiamento e Investimento' },
  { codigo: '352', nome: 'Toro Corretora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '354', nome: 'Necton Investimentos S.A. Corretora de Valores Mobiliários e Commodities' },
  { codigo: '355', nome: 'Ótimo Sociedade de Crédito Direto S.A.' },
  { codigo: '356', nome: 'Banco Real S.A.' },
  { codigo: '359', nome: 'Zema Crédito, Financiamento e Investimento S/A' },
  { codigo: '360', nome: 'Trinus Capital Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '362', nome: 'Cielo S.A.' },
  { codigo: '363', nome: 'Socopa Sociedade Corretora Paulista S.A.' },
  { codigo: '364', nome: 'Gerencianet Pagamentos do Brasil Ltda' },
  { codigo: '365', nome: 'Solidus S.A. Corretora de Câmbio e Valores Mobiliários' },
  { codigo: '366', nome: 'Banco Société Générale Brasil S.A.' },
  { codigo: '370', nome: 'Banco Mizuho do Brasil S.A.' },
  { codigo: '376', nome: 'Banco J. P. Morgan S.A.' },
  { codigo: '380', nome: 'PicPay Serviços S.A.' },
  { codigo: '381', nome: 'Banco Mercedes-Benz do Brasil S.A.' },
  { codigo: '382', nome: 'Fiducia Scmepp Ltda.' },
  { codigo: '383', nome: 'Juno' },
  { codigo: '384', nome: 'Global SCM Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte Ltda.' },
  { codigo: '385', nome: 'Cooperativa de Economia e Crédito Mútuo dos Empregados do Grupo Corpvs' },
  { codigo: '386', nome: 'Nu Financeira S.A. – Sociedade de Crédito, Financiamento e Investimento' },
  { codigo: '387', nome: 'Banco Toyota do Brasil S.A.' },
  { codigo: '389', nome: 'Banco Mercantil do Brasil S.A.' },
  { codigo: '390', nome: 'Banco GM S.A.' },
  { codigo: '391', nome: 'Cooperativa de Crédito Rural – Sulcredi/Cobel' },
  { codigo: '393', nome: 'Banco Volkswagen S.A.' },
  { codigo: '394', nome: 'Banco Bradesco Financiamentos S.A.' },
  { codigo: '395', nome: 'F.D\'Gold – Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '396', nome: 'Hub Pagamentos S.A.' },
  { codigo: '397', nome: 'Listo Sociedade de Crédito Direto S.A.' },
  { codigo: '398', nome: 'Ideal Corretora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '399', nome: 'Kirton Bank S.A. – Banco Múltiplo' },
  { codigo: '400', nome: 'Cooperativa de Crédito, Poupança e Serviços Financeiros do Centro Oeste' },
  { codigo: '401', nome: 'Iugu Instituição de Pagamento S.A.' },
  { codigo: '402', nome: 'Cobuccio S.A. Sociedade de Crédito, Financiamento e Investimentos' },
  { codigo: '403', nome: 'Cora Sociedade de Crédito Direto S.A.' },
  { codigo: '404', nome: 'Sumup Sociedade de Crédito Direto S.A.' },
  { codigo: '406', nome: 'Accredito – Sociedade de Crédito Direto S.A.' },
  { codigo: '408', nome: 'Bonuspago Sociedade de Crédito Direto S.A.' },
  { codigo: '410', nome: 'Planner Sociedade de Crédito ao Microempreendedor S.A.' },
  { codigo: '411', nome: 'Via Certa Financiadora S.A. – Crédito, Financiamento e Investimentos' },
  { codigo: '412', nome: 'Banco Capital S.A.' },
  { codigo: '413', nome: 'Banco BV S.A.' },
  { codigo: '414', nome: 'Work Sociedade de Crédito Direto S.A.' },
  { codigo: '415', nome: 'Lamara Sociedade de Crédito Direto S.A.' },
  { codigo: '422', nome: 'Banco Safra S.A.' },
  { codigo: '423', nome: 'Toro CTVM Ltda.' },
  { codigo: '425', nome: 'Socinal S.A. – Crédito, Financiamento e Investimento' },
  { codigo: '426', nome: 'Biorc Financeira – Crédito, Financiamento e Investimento S.A.' },
  { codigo: '427', nome: 'Cooperativa de Crédito dos Servidores da Universidade Federal do Espírito Santo' },
  { codigo: '428', nome: 'Credsystem Sociedade de Crédito Direto S.A.' },
  { codigo: '429', nome: 'Crediare S.A. – Crédito, Financiamento e Investimento' },
  { codigo: '430', nome: 'Cooperativa de Crédito Rural Seara – Crediseara' },
  { codigo: '433', nome: 'BR-Capital Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '435', nome: 'Delcred Sociedade de Crédito Direto S.A.' },
  { codigo: '438', nome: 'Planner Trustee Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '439', nome: 'ID Corretora de Títulos e Valores Mobiliários S.A.' },
  { codigo: '440', nome: 'Credibrf – Cooperativa de Crédito' },
  { codigo: '441', nome: 'Magnetis – Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '442', nome: 'Ássio Corretora de Câmbio e Títulos e Valores Mobiliários Ltda.' },
  { codigo: '443', nome: 'Credihome Sociedade de Crédito Direto S.A.' },
  { codigo: '444', nome: 'Trinus Sociedade de Crédito Direto S.A.' },
  { codigo: '445', nome: 'Plantae S.A. – Crédito, Financiamento e Investimento' },
  { codigo: '446', nome: 'Mirae Asset Wealth Management (Brazil) CCTVM Ltda.' },
  { codigo: '447', nome: 'Mirae Asset Wealth Management (Brazil) CCTVM Ltda.' },
  { codigo: '448', nome: 'Hemera Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '449', nome: 'Dmcard Sociedade de Crédito Direto S.A.' },
  { codigo: '450', nome: 'Fitbank Pagamentos Eletrônicos S.A.' },
  { codigo: '451', nome: 'J17 – Sociedade de Crédito Direto S/A' },
  { codigo: '452', nome: 'Credifit Sociedade de Crédito Direto S.A.' },
  { codigo: '453', nome: 'Mérito Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '454', nome: 'Mérito Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '455', nome: 'Fênix Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '456', nome: 'Banco MUFG Brasil S.A.' },
  { codigo: '457', nome: 'UY3 Sociedade de Crédito Direto S/A' },
  { codigo: '458', nome: 'Hedge Investments Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '459', nome: 'CCM Cooperativa de Crédito, Poupança e Investimento dos Profissionais das Ciências Contábeis' },
  { codigo: '460', nome: 'Unavanti Sociedade de Crédito Direto S/A' },
  { codigo: '461', nome: 'Asaas Gestão Financeira Instituição de Pagamento S.A.' },
  { codigo: '462', nome: 'Stark Bank S.A. – Instituição de Pagamento' },
  { codigo: '463', nome: 'Azumi Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { codigo: '464', nome: 'Banco Sumitomo Mitsui Brasileiro S.A.' },
  { codigo: '465', nome: 'Capital Consig Sociedade de Crédito Direto S.A.' },
  { codigo: '467', nome: 'Master S/A Corretora de Câmbio, Títulos e Valores Mobiliários' },
  { codigo: '468', nome: 'Portoseg S.A. – Crédito, Financiamento e Investimento' },
  { codigo: '469', nome: 'Picpay Bank – Banco Múltiplo S.A.' },
  { codigo: '470', nome: 'CDC Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte S.A.' },
  { codigo: '471', nome: 'Gazincred S.A. Sociedade de Crédito, Financiamento e Investimento' },
  { codigo: '473', nome: 'Banco Caixa Geral – Brasil S.A.' },
  { codigo: '477', nome: 'Citibank N.A.' },
  { codigo: '479', nome: 'Banco ItauBank S.A.' },
  { codigo: '487', nome: 'Deutsche Bank S.A. – Banco Alemão' },
  { codigo: '488', nome: 'JPMorgan Chase Bank, National Association' },
  { codigo: '492', nome: 'ING Bank N.V.' },
  { codigo: '495', nome: 'Banco de La Provincia de Buenos Aires' },
  { codigo: '505', nome: 'Banco Credit Suisse (Brasil) S.A.' },
  { codigo: '545', nome: 'Senso Corretora de Câmbio e Valores Mobiliários S.A.' },
  { codigo: '600', nome: 'Banco Luso Brasileiro S.A.' },
  { codigo: '604', nome: 'Banco Industrial do Brasil S.A.' },
  { codigo: '610', nome: 'Banco VR S.A.' },
  { codigo: '611', nome: 'Banco Paulista S.A.' },
  { codigo: '612', nome: 'Banco Guanabara S.A.' },
  { codigo: '613', nome: 'Omni Banco S.A.' },
  { codigo: '623', nome: 'Banco Pan S.A.' },
  { codigo: '626', nome: 'Banco C6 Consignado S.A.' },
  { codigo: '630', nome: 'Banco Smartbank S.A.' },
  { codigo: '633', nome: 'Banco Rendimento S.A.' },
  { codigo: '634', nome: 'Banco Triângulo S.A.' },
  { codigo: '637', nome: 'Banco Sofisa S.A.' },
  { codigo: '643', nome: 'Banco Pine S.A.' },
  { codigo: '652', nome: 'Itaú Unibanco Holding S.A.' },
  { codigo: '653', nome: 'Banco Indusval S.A.' },
  { codigo: '654', nome: 'Banco A.J. Renner S.A.' },
  { codigo: '655', nome: 'Banco Votorantim S.A.' },
  { codigo: '707', nome: 'Banco Daycoval S.A.' },
  { codigo: '712', nome: 'Banco Ourinvest S.A.' },
  { codigo: '720', nome: 'Banco RNX S.A.' },
  { codigo: '739', nome: 'Banco Cetelem S.A.' },
  { codigo: '741', nome: 'Banco Ribeirão Preto S.A.' },
  { codigo: '743', nome: 'Banco Semear S.A.' },
  { codigo: '745', nome: 'Banco Citibank S.A.' },
  { codigo: '746', nome: 'Banco Modal S.A.' },
  { codigo: '747', nome: 'Banco Rabobank International Brasil S.A.' },
  { codigo: '748', nome: 'Banco Cooperativo Sicredi S.A.' },
  { codigo: '751', nome: 'Scotiabank Brasil S.A. Banco Múltiplo' },
  { codigo: '752', nome: 'Banco BNP Paribas Brasil S.A.' },
  { codigo: '753', nome: 'Novo Banco Continental S.A. – Banco Múltiplo' },
  { codigo: '754', nome: 'Banco Sistema S.A.' },
  { codigo: '755', nome: 'Bank of America Merrill Lynch Banco Múltiplo S.A.' },
  { codigo: '756', nome: 'Banco Cooperativo do Brasil S.A. – Bancoob (Sicoob)' },
  { codigo: '757', nome: 'Banco KEB Hana do Brasil S.A.' },
]
