const fs = require('fs')
const path = require('path')

function assert(condition, message) {
  if (!condition) throw new Error(message)
}

const service = fs.readFileSync(path.join(__dirname, '../src/services/stratoIntelligentApplyService.js'), 'utf8')
const route = fs.readFileSync(path.join(__dirname, '../src/routes/recebiveis.js'), 'utf8')
const analyzer = fs.readFileSync(path.join(__dirname, '../src/services/stratoMultiParcelAnalysisService.js'), 'utf8')

assert(service.includes("'v2'"), 'Chave de seleção estável v2 ausente.')
assert(service.includes('selectionPart(filename)'), 'A chave precisa incluir o arquivo do retorno.')
assert(service.includes('analysisItem?.linha'), 'A chave continua preservando a linha física do retorno para auditoria.')
assert(service.includes('parcelAnalysis?.parcela?.id'), 'A chave precisa usar a parcela localizada como identidade estável.')
assert(!service.includes('return `${fileIndex}:${itemIndex}:${parcelIndex}`'), 'A seleção não pode depender da posição dos arrays.')
assert(service.includes('unmatchedSelections'), 'Seleções não reconhecidas não podem terminar como sucesso silencioso.')
assert(service.includes('parseStableSelectionKey'), 'A aplicação precisa interpretar a identidade enviada pelo frontend.')
assert(service.includes('buildIdentityCounts'), 'A identidade alternativa precisa ser única dentro da análise recalculada.')
assert(service.includes('resolveSelectionKey'), 'A aplicação precisa aceitar a parcela estável mesmo quando a linha CNAB muda.')
assert(service.includes('entry.identity === identity'), 'A recuperação precisa comparar a identidade real da parcela.')
assert(service.includes('identificador antigo por posição'), 'Frontend antigo precisa ser recusado com mensagem explícita.')
assert(service.includes("'ATUALIZAR_E_BAIXAR'"), 'Atualização e baixa não está habilitada.')
assert(service.includes("'CRIAR_PARCELA_E_BAIXAR'"), 'Criação segura de parcela não está habilitada.')
assert(service.includes("'CLIENTE_AUSENTE'"), 'Cliente ausente deve permanecer bloqueado.')
assert(service.includes("'CONTRATO_AMBIGUO'"), 'Contrato ambíguo deve permanecer bloqueado.')
assert(service.includes('FOR UPDATE'), 'A aplicação precisa bloquear registros antes da escrita.')
assert(service.includes('pg_advisory_xact_lock'), 'A aplicação deve impedir movimentos duplicados em requisições concorrentes.')
assert(service.includes('movimentos_individuais') || service.includes('movimento_id'), 'A aplicação deve preservar movimentos individuais.')
assert(service.includes('valor_desconto'), 'O desconto precisa ser gravado separadamente.')
assert(service.includes('data_recebimento'), 'A data de recebimento do Strato precisa ser preservada.')
assert(service.includes('A aplicação foi cancelada'), 'Falha em uma seleção deve cancelar a transação.')
assert(route.includes('aplicar_analise_inteligente'), 'A rota precisa aceitar a aplicação aprovada pelo frontend.')
assert(route.includes('selecoes_inteligentes'), 'A rota precisa receber somente as seleções do usuário.')
assert(route.includes('contas_receber_retorno_strato_aplicacao_inteligente'), 'Auditoria da aplicação não foi encontrada.')
assert(analyzer.includes("versao: '0.6.5'"), 'A análise financeira base 0.6.5 precisa ser preservada.')

console.log('Aplicação inteligente Strato 0.6.7: identidade da parcela preservada mesmo com mudança de linha, transação e bloqueio de falso sucesso conferidos.')
